---

- name: Instalar make, gmake, ansible y pip3
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - make
    - build-essential
    - ansible
    - python3-pip
    - python3.9-distutils


- name: Instalar modulo python openshift
  ansible.builtin.pip:
    name: openshift
    state: present


- name: Descargar repo AWX de Github
  ansible.builtin.git:
    repo: "https://github.com/ansible/awx.git"
    dest: "{{ path }}"
    version: "{{ version }}"


- name: Ejecutar Make instalación
  community.general.make:
    chdir: "{{ path }}"
    target: docker-compose-container-group
    params:
      MINIKUBE_CONTAINER_GROUP: true
      MINIKUBE_SETUP: true

...