---

- name: Crear carpeta
  ansible.builtin.file:
    path: "{{ path }}"
    state: directory
    mode: '0755'


- name: Copiar template kustomization.yml
  ansible.builtin.template:
    src: kustomization.yml.j2
    dest: "{{ path }}/kustomization.yml"
    mode: '644'


- name: Ejecutar kustomization.yml
  ansible.builtin.shell:
    chdir: "{{ path }}"
    cmd: kubectl apply -k .
  become: false


- name: Añadir linea a fichero kustomization
  ansible.builtin.lineinfile:
    path: "{{ path }}/kustomization.yml"
    insertafter: "- github.com/ansible/awx-operator"
    regexp: "- github.com/ansible/awx-operator"
    line: "  - awx-demo.yml"


- name: Copiar awx-demo.yml
  ansible.builtin.copy:
    src: awx-demo.yml
    dest: "{{ path }}"
    mode: '0644'


- name: Ejecutar kustomization.yml
  ansible.builtin.shell:
    chdir: "{{ path }}"
    cmd: kubectl apply -k .
  become: false


- name: Requirements python modulo kubernetes
  ansible.builtin.include_tasks: requirements.yml


- name: Esperar a creacion de pods
  kubernetes.core.k8s_info:
    kind: Deployment
    wait: yes
    name: "{{ item }}"
    namespace: awx
    wait_timeout: 2000
    wait_sleep: 10
  loop:
    - awx-operator-controller-manager
    - awx-demo-task
    - awx-demo-web
  become: false


- name: Obtener url de minikube
  ansible.builtin.command:
    cmd: minikube service -n awx awx-demo-service --url
  register: url
  become: false


- name: Dividir la URL en una lista
  ansible.builtin.set_fact:
    url_parts: "{{ url.stdout.split(':') }}"


- name: Obtener password admin AWX
  kubernetes.core.k8s_info:
    kind: Secret
    name: awx-demo-admin-password
    namespace: awx
  register: password
  become: false


- name: Añadir dominio a /etc/host
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ url_parts[1][2::] }}  awx.local"


- name: Msg url, usuario, password
  ansible.builtin.debug:
    msg: "url: awx.local:{{ url_parts[2]}} ({{ url_parts[1][2::] }}:{{ url_parts[2]}})  user:admin   password:{{ password.resources[0].data.password | b64decode }}"

...