---

- name: Instalar pip
  ansible.builtin.package:
    name: python3-pip
    state: present
    update_cache: true


- name: Instalar librerias python
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop:
    - kubernetes
    - pyyaml

...