---

- name: Instalar Kubectl
  block:
    - name: Comprobar si kubectl está instalado
      ansible.builtin.command:
        cmd: kubectl --help

    - name: Msg kubectl instalado
      ansible.builtin.debug:
        msg: "Kubectl esta instalado"
  rescue:
    - name: Descargar paquete 
      ansible.builtin.uri:
        url: https://dl.k8s.io/release/v{{ version }}/bin/linux/amd64/kubectl
        dest: "{{ path }}"

    - name: Instalar kubectl
      ansible.builtin.copy:
        src: "{{ path }}/kubectl"
        dest: /usr/bin/kubectl
        owner: root
        group: root
        mode: '0755'
        remote_src: true

    - name: Eliminar paquete
      ansible.builtin.file:
        path: "{{ path }}/kubectl"
        state: absent

...