---

- name: Descargar paquete 
  ansible.builtin.uri:
    url: https://dl.k8s.io/release/v{{ version }}/bin/linux/amd64/kubectl
    dest: "{{ path }}"


- name: Instalar kubectl
  ansible.builtin.copy:
    src: "{{ path }}/kubectl"
    dest: /usr/local/bin/kubectl
    owner: root
    group: root
    mode: '0755'
    remote_src: true


- name: Eliminar paquete
  ansible.builtin.file:
    path: "{{ path }}/kubectl"
    state: absent

...