---

- name: Instalar Kubectl
  block:
    - name: Comprobar si kubectl está instalado
      ansible.builtin.command:
        cmd: kubectl --help

    - name: Msg kubectl instalado
      ansible.builtin.debug:
        msg: "Kubectl esta instalado"
  rescue:
    - name: Descargar e instalar paquete 
      ansible.builtin.get_url:
        url: https://dl.k8s.io/release/v{{ version }}/bin/linux/amd64/kubectl
        dest: "{{ path }}/kubectl"
        owner: root
        group: root
        mode: '0755'

...