---

- name: Descargar paquete 
  ansible.builtin.uri:
    url: https://dl.k8s.io/release/v{{ version }}/bin/linux/amd64/kubectl
    dest: "{{ path }}"


- name: Instalar kubectl
  ansible.builtin.command:
    chdir: "{{ path }}"
    cmd: install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl


- name: Eliminar paquete
  ansible.builtin.file:
    path: "{{ path }}/kubectl"
    state: absent

...