---

- name: Block Redhat
  when: ansible_os_family == "RedHat"
  block:
    - name: A침adir repo docker
      ansible.builtin.yum_repository:
        name: Docker
        description: Docker
        baseurl: https://download.docker.com/linux/centos/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/stable/
        gpgcheck: no


- name: Instalaci칩n Docker
  block:
    - name: Comprobar instalacion docker
      ansible.builtin.command:
        cmd: docker --version
      register: docker

    - name: Debug docker
      ansible.builtin.debug:
        msg: "Docker instalado en la version:{{ docker.stdout[14:23] }}"
  rescue:
    - name: Instalar docker 
      ansible.builtin.package:
        name: "{{ paquete_docker }}"
        state: present
        update_cache: true


- name: Instalaci칩n Docker compose
  block:
    - name: Comprobar instalacion docker compose
      ansible.builtin.stat:
        path: /usr/local/bin/docker-compose
      register: compose

    - name: Debug compose
      ansible.builtin.assert:
        that: compose.stat.exists
        success_msg: "Docker compose instalado en la version: {{ version_compose }}"
  rescue:
    - name: Instalar docker-compose
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/v{{ version_compose}}/docker-compose-Linux-{{ ansible_architecture }}
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Dar permisos de ejecucion a docker-compose
      ansible.builtin.file:
        path: /usr/local/bin/docker-compose
        owner: root
        group: root
        mode: '0755'
        state: file


- name: A침adir usuario a grupo docker
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  register: user


- name: Reiniciar equipo
  ansible.builtin.reboot:
    reboot_timeout: 300
  when: user.changed


- name: Levantar servicio docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
            
...